### ISSUE TITLE
How to understand the "probability" in the heatmap

### ISSUE THREAD

**Issue by joe-jhou2** [RGLab/COMPASS#61]
Can I interpret the probability as a percentage of each subset? I'm confused on this concept. Per the total T cells, if some cells defined as only IFNG expression, then shouldn't be counted for IFNG and IL2 expression, presumably, the total percentage should be 100% for all subset. In this case, it seems the interpretation of probability as the percentage is wrong. Becuase in your example, some subsets have almost 1 probability in one sample, the sum of them exceed 100%.  Can you explain?

**Comment by mimisikai** [comment]
Just curious, I assume the COMPASS would be able to extract the cytokines positive cells from total CD4 T cells, why do not just show the % of each cell subset in total CD4 T cells? That will be easy for people to understand the results.

**Comment by gfinak** [comment]
If you read the COMPASS paper carefully you would see the comparison of the posterior probablities against the cell population proportions.
The cell proportions are noisy and mitigating  that noise is the whole point of the statistical modeling exercise.

**Comment by mimisikai** [comment]
Yes, I see that. Sometimes, the reality is, at least in our lab, the problem we're facing, we're running fresh samples, which means, each sample could be considered as a batch, that's great challenge for normalization in order to liquidate the batch effects. I sense lots of approaches are using intensity instead of %, that may lead to misunderstand on the data set like mine, with tremendous batch effects that so difficult to eliminate/normalize.

**Comment by gfinak** [comment]
Batch specific gating should mitigate such issues, provided that all stimulation conditions for a given sample are run as part of the same batch.
